services:
  - type: web
    name: fitcoach-backend
    runtime: docker
    repo: https://github.com/Martha476/HEALTH-FITNESS-COACH
    branch: master
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: DEBUG
        value: False
      - key: ENABLE_AUTH
        value: True
      - key: ENABLE_FEEDBACK
        value: True
      - key: ENABLE_RETRY
        value: True
      - key: ENABLE_TOKEN_TRACKING
        value: True
      - key: ENABLE_CACHE
        value: False
      - key: ENABLE_RAG
        value: False