-- Email Verification Database Migration
-- Run this in Supabase SQL Editor to add email verification support
-- Date: April 21, 2026

-- ============================================================
-- Add Email Verification Columns to Users Table
-- ============================================================

-- Add email_verified column (tracks if email is verified)
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT FALSE;

-- Add email_verified_at column (timestamp when email was verified)
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMP NULL;

-- Create index on email_verified for faster queries
CREATE INDEX IF NOT EXISTS idx_users_email_verified ON users(email_verified);

-- Create index on email for faster lookups
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- ============================================================
-- Optional: Create Email Verification Tokens Table
-- (Use this if moving away from in-memory token storage)
-- ============================================================

/*
CREATE TABLE IF NOT EXISTS email_verification_tokens (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) UNIQUE NOT NULL,
    token VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_verification_tokens_email 
ON email_verification_tokens(email);

CREATE INDEX IF NOT EXISTS idx_verification_tokens_expires_at 
ON email_verification_tokens(expires_at);

-- This helps with cleanup: DELETE FROM email_verification_tokens WHERE expires_at < NOW();
*/

-- ============================================================
-- Verify the Changes
-- ============================================================

-- Check that columns were added
-- SELECT column_name, data_type FROM information_schema.columns 
-- WHERE table_name = 'users' AND column_name IN ('email_verified', 'email_verified_at');

-- ============================================================
-- Data Migration (Optional: for existing users)
-- ============================================================

-- Option 1: Mark all existing users as verified (for testing)
-- UPDATE users SET email_verified = TRUE, email_verified_at = NOW() WHERE email_verified IS NULL;

-- Option 2: Keep existing users unverified (more secure)
-- UPDATE users SET email_verified = FALSE WHERE email_verified IS NULL;

-- ============================================================
-- Post-Migration Checks
-- ============================================================

-- Check updated users table structure
-- SELECT * FROM users LIMIT 1;

-- Count verified vs unverified users
-- SELECT email_verified, COUNT(*) as count FROM users GROUP BY email_verified;

-- ============================================================
-- Complete! Notes:
-- ============================================================
-- 1. If you used Option 1: all users are marked as verified and can login
-- 2. If you used Option 2: users must verify email first
-- 3. The email_verification_tokens table is optional
--    (currently using in-memory storage, but DB is recommended for production)
-- 4. Uncomment and run the verification checks to confirm changes
